_wandb:
    value:
        cli_version: 0.26.1
        e:
            5fvsjy0bqlldzolusi581o4rv9s1we4p:
                args:
                    - --base_dir
                    - C:/Users/T2430397/Documents/bangla-sign-language-recognition-main
                    - --epochs
                    - "100"
                    - --use_amp
                    - --split_mode
                    - active
                    - --loader_error_mode
                    - permissive
                    - --gradient_accumulation_steps
                    - "2"
                codePath: new model\BdSL-Enhanced-SignNet\train_signet_v2_optimized.py
                codePathLocal: new model\BdSL-Enhanced-SignNet\train_signet_v2_optimized.py
                cpu_count: 20
                cpu_count_logical: 28
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "999275098112"
                        used: "244614586368"
                email: aronno902553@gmail.com
                executable: C:\Users\T2430397\Documents\bangla-sign-language-recognition-main\.venv\Scripts\python.exe
                git:
                    commit: 873fd4e95084aa8a344e7f2de087d52a70c5b376
                    remote: https://github.com/sajiiid09/bangla-sign-language-recognition.git
                gpu: NVIDIA GeForce RTX 4080 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 10240
                      memoryTotal: "17171480576"
                      name: NVIDIA GeForce RTX 4080 SUPER
                      uuid: GPU-2a5c25d0-1f73-919b-fd8b-f6f0df709aaf
                host: CSE-12B21L-D20
                memory:
                    total: "68470374400"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\T2430397\Documents\bangla-sign-language-recognition-main\new model\BdSL-Enhanced-SignNet\train_signet_v2_optimized.py
                python: CPython 3.14.4
                root: C:\Users\T2430397\Documents\bangla-sign-language-recognition-main
                startedAt: "2026-04-27T12:19:42.719116Z"
                writerId: 5fvsjy0bqlldzolusi581o4rv9s1we4p
        m: []
        python_version: 3.14.4
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 1
                - 2
                - 13
                - 16
            "4": 3.14.4
            "5": 0.26.1
            "8":
                - 3
            "12": 0.26.1
            "13": windows-amd64
batch_size:
    value: 16
epochs:
    value: 100
gradient_accumulation_steps:
    value: 2
learning_rate:
    value: 0.0003
loader_error_mode:
    value: permissive
num_classes:
    value: 67
seed:
    value: 42
split_mode:
    value: active
split_signer_distribution:
    value:
        test:
            S02: 74
            S04: 2
            S05: 123
            S10: 81
        train:
            S02: 414
            S04: 16
            S05: 909
            S10: 460
        val:
            S02: 54
            S04: 2
            S05: 111
            S10: 60
split_summary_exists:
    value: true
split_summary_path:
    value: C:\Users\T2430397\Documents\bangla-sign-language-recognition-main\Data\processed\new_model\split_summary.json
use_amp:
    value: true
